In [1]:
import pandas as pd 
import numpy as np
print("sab ready hai!")

sab ready hai!

In [3]:
data ={"name":["Riya","Kanika","Aniket"],"marks":[85,90,98]}
df = pd.DataFrame(data)
df

     name  marks
0    Riya     85
1  Kanika     90
2  Aniket     98

In [6]:
df["marks"].mean()

np.float64(91.0)

In [7]:
df.describe()

           marks
count   3.000000
mean   91.000000
std     6.557439
min    85.000000
25%    87.500000
50%    90.000000
75%    94.000000
max    98.000000